services:
  backend:
    build: ./backend
    ports: ["5001:5001"]
    environment:
      - PORT=5001
      - ANILIST_URL=https://graphql.anilist.co
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    environment:
      - VITE_API_BASE=http://localhost:5001
    depends_on:
      - backend


  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
